In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
np.__version__

'1.21.6'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-22 21:45:47--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.04s

2022-09-22 21:45:47 (37.3 MB/s) - ‘data.csv’ saved [1475504/1475504]

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df.shape

(11914, 16)

In [6]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [7]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker              3
Genesis             3
Bugatti             3
Name: Make, dtype: int64

##Question 4
What's the number of unique Audi car models in the dataset?

In [9]:
#df[['Make']]=='Audi'.nunique()
df[df['Make'] == 'Audi']['Model'].nunique()

34

##Question 5
How many columns in the dataset have missing values?

In [ ]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

##Question 6


Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

1.   Find the median value of "Engine Cylinders" column in the dataset.

In [11]:
df['Engine Cylinders'].median()

6.0

2.   Next, calculate the most frequent value of the same "Engine Cylinders".

In [13]:
df['Engine Cylinders'].mode()

0    4.0
dtype: float64



3.   Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

In [15]:
mode_fill = df['Engine Cylinders'].mode()[0]
mode_fill

4.0



4.   Now, calculate the median value of "Engine Cylinders" once again.

In [16]:
df['Engine Cylinders'].fillna(mode_fill).median()

6.0

##Question 7



1.   Select all the "Lotus" cars from the dataset.

In [19]:
lotus = df[df['Make'] == 'Lotus']
lotus

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
3912,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3913,Lotus,Elise,2009,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3914,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3915,Lotus,Elise,2010,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3917,Lotus,Elise,2011,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3918,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3919,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4216,Lotus,Esprit,2002,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4217,Lotus,Esprit,2003,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4218,Lotus,Esprit,2004,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4257,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4258,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4260,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4261,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4262,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4263,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4264,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4265,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4266,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4267,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4268,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4292,Lotus,Exige,2009,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4293,Lotus,Exige,2009,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4294,Lotus,Exige,2010,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2011,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4297,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950



1.   Select only columns "Engine HP", "Engine Cylinders".

In [21]:
lotus = lotus[['Engine HP', 'Engine Cylinders']]
lotus

      Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0